### PR TITLE
fix(react): 🐛 avoid creating browser-specific objects in SSR environment

### PR DESCRIPTION
**Pull request by sheey11**
## Description

When using SSR, following error will be throwed:

```plain
 ⨯ Internal error: ReferenceError: IntersectionObserver is not defined
    at eval (./node_modules/.pnpm/@lottiefiles+dotlottie-react@0.5.9_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@lottiefiles/dotlottie-react/dist/index.js:1812:5)
    at Object.oN [as useMemo] (/home/sheey/proj/node_modules/.pnpm/next@14.2.2_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:12:68806)
```

`useMemo` hook is used to create `IntersectionObserver`, which will be excuted on server, causing the error.

https://github.com/LottieFiles/dotlottie-web/blob/d59b55d859cafe7c2d2474bf0e9f9e675542ef86/packages/react/src/use-dotlottie.tsx#L82-L96

A solution is to delay the assignment by replacing `useMemo` with `useEffect`.

## Type of change

- [x]  Patch: Bug (non-breaking change which fixes an issue)
- [ ]  Minor: New feature (non-breaking change which adds functionality)
- [ ]  Major: Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [ ] This is something we need to do.

### CODE REVIEW

**Review by theashraf — COMMENTED** [review]
Thanks for your contribution @sheey11 🙏🏼 

In my opinion, we still should consider lazy initialization and create the `IntersectionObserver` and `ResizeObserver` only when rendering on the client on pre rendering. This approach eliminates the need for updating the observers using `useEffect` after the component is mounted, and scheduling another state update. 

We can update the `useMemo` where we lazy initialize the observers this way:

```jsx
const intersectionObserver = useMemo(() => {
  const observerCallback = debounce((entries: IntersectionObserverEntry[]) => {
    entries.forEach((entry) => {
      if (entry.isIntersecting) {
        dotLottieRef.current?.unfreeze();
      } else {
        dotLottieRef.current?.freeze();
      }
    });
  }, 150);

  return isSSR()
    ? null
    : new IntersectionObserver(observerCallback, {
        threshold: 0,
      });
}, []);

const resizeObserver = useMemo(() => {
  const observerCallback = debounce(() => {
    if (configRef.current?.autoResizeCanvas) {
      dotLottieRef.current?.resize();
    }
  }, 150);

  return isSSR() ? null : new ResizeObserver(observerCallback);
}, []);
```

What do you think ?

**Comment by sheey11** [comment]
Sounds good!  
I will change it in next commit.

**Comment by sheey11** [comment]
I wonder if there's another bug...

https://github.com/LottieFiles/dotlottie-web/blob/88326766887b315078010c862d455839e23ae86f/packages/react/src/use-dotlottie.tsx#L61
https://github.com/LottieFiles/dotlottie-web/blob/88326766887b315078010c862d455839e23ae86f/packages/react/src/use-dotlottie.tsx#L160-L171

since the dependency list is empty, `dotLottie` will remain its first value `null`, meaning the instance will never be destroyed.

**Comment by theashraf** [comment]
> I wonder if there's another bug...
> 
> https://github.com/LottieFiles/dotlottie-web/blob/88326766887b315078010c862d455839e23ae86f/packages/react/src/use-dotlottie.tsx#L61
> 
> 
> https://github.com/LottieFiles/dotlottie-web/blob/88326766887b315078010c862d455839e23ae86f/packages/react/src/use-dotlottie.tsx#L160-L171
> 
> since the dependency list is empty, `dotLottie` will remain its first value `null`, meaning the instance will never be destroyed.

The dotLottie is created only once when the canvas ref is initialized, which is always going to happen before the useEffect cleanup

**Review by theashraf — APPROVED** [review]

**Pull request merged**
